import typing

from kubernetes.client.api_client import ApiClient

class LogsApi:
    def __init__(self, api_client: typing.Optional[ApiClient] = ...) -> None: ...
    def log_file_list_handler(self) -> None: ...
    def log_file_handler(self, logpath: str) -> None: ...
